name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc tên branch chính của bạn (master/main)

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Thư mục chứa kết quả build của Vite
          branch: gh-pages # Tên branch để GitHub Pages hiển thị (có thể tùy chỉnh trong Settings)
